# Generated by Django 4.1.4 on 2023-01-09 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0006_alter_preguntasrespondidas_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='quizUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intento', to='quizz.quizusuario'),
        ),
    ]
